# Generated by Django 4.2 on 2023-04-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('host', models.URLField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('set_cookie', models.TextField(blank=True, default='')),
                ('set_cookie_expires', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
