# Generated by Django 4.2 on 2023-04-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_server_set_cookie_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='set_cookie_expires',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
