# Generated by Django 4.2 on 2023-04-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0004_server_owner_server_sort_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='viewer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_viewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='server_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
