# Generated by Django 4.2 on 2023-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_server_viewer_alter_server_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_disabled_users',
            field=models.TextField(blank=True, default=''),
        ),
    ]
