# Generated by Django 4.2 on 2023-05-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_server_last_disabled_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
