# Generated by Django 4.2 on 2023-05-05 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0007_alter_server_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='viewer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='server_viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
